### ISSUE TITLE
Issue with Resistance update

### ISSUE THREAD

**Issue by Teo1904** [Zutatensuppe/DiabloInterface#2]
Hi,

I noticed yesterday that the shown resistances get updated, but not for the difficulty i am actually in.
I made a video to clarify this a little more:
https://youtu.be/Wy2EqEnXpl0
It Shows that on nightmare it shows the resistances of normal. Yes they get updated when I change resistances on my gear, but it just shows the resistances how they would be in normal.

That is a big issue for viewers that are really curious about those. ;)

greetz Teo1904

**Comment by rotacioskapa** [comment]
Hi Teo, Cubeholder here, i have sent a pull request with the fix for this issue.

**Comment by Teo1904** [comment]
lets assume I have no idea what that means. ;) does Zutatensuppe have to update it to 0.2.6 or how do I use that? :P

**Comment by Zutatensuppe** [comment]
Kind of. :dancer:  I merged the changes and attached the files here. Can u try with the attached file before I add it as a release?
[build.zip](https://github.com/Zutatensuppe/DiabloInterface/files/292227/build.zip)

**Comment by Teo1904** [comment]
Yes that works. this issue is fixed. ;)

**Comment by Zutatensuppe** [comment]
It seems that the issue is still not resolved completely. (see teos wr run in HC necro hell race)
